Enable HTTP/2 by default
cloudfoundry/routing-release pull request #215
Opened 2021-07-28 18:54 UTC by ctlong

* A short explanation of the proposed change:
  `router.enable_http2` will be true by default. The property description no longer describes this as a beta feature, in keeping with what it currently says

* Links to any other associated PRs
  Gorouter PR coming soon

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [ ] I have run all the unit tests using `scripts/run-unit-tests-in-docker`

* [ ] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests on bosh lite

* [ ] (Optional) I have run CF Acceptance Tests on bosh lite

2021-08-11 20:24 UTC, ameowlia commented
Let's wait to merge this until the [CC PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/2439) is merged and users can actually use this full feature.

2021-08-19 23:25 UTC, ctlong commented
@ameowlia the CC PR has been merged. Is there anything else we need to do for this PR and cloudfoundry/gorouter#292?

2021-08-27 16:57 UTC, ameowlia requested changes
* Let's edit this description to show that this enables http/2 for two different hops
* also lets provide docs that link to capi or something about how to set the protocol for a route to h2

2021-08-27 16:57 UTC, ameowlia commented on jobs/gorouter/spec
> +    description: Enables the option to use the HTTP/2 protocol for communicating with backends.
Enables end users to send HTTP/2 traffic to the Gorouter. Also enables the option to use the HTTP/2 protocol for communicating with specified backends. See [TODO link to doc here]() for more info on how to mark routes as HTTP/2 compatible.

2021-08-27 17:06 UTC, ameowlia commented
Waiting to merge on:
* pipelines envs to be h2 compatible so we can run h2 cats before we cut a release

2021-08-27 17:54 UTC, ctlong commented on jobs/gorouter/spec
> +    description: Enables the option to use the HTTP/2 protocol for communicating with backends.
I don't believe that we have a doc with that info right now, the story to make it is further down our backlog. The closest thing would probably be our tracking issue: #200. If that's not enough, and I don't think it is for this ask, then we need to wait on that as well.

2021-08-30 17:25 UTC, Gerg commented on jobs/gorouter/spec
> +    description: Enables the option to use the HTTP/2 protocol for communicating with backends.
@ameowlia Are you looking for [API docs like these](https://v3-apidocs.cloudfoundry.org#the-destination-object) or something on https://docs.cloudfoundry.org/?

2021-08-31 22:37 UTC, Gerg commented
I updated the description to mention both ingress and egress traffic. Based on our investigation, the routing pipeline environments should be compatible with HTTP/2 (assuming they have the correct versions of capi/routing/diego-release).

2021-09-07 15:12 UTC, ameowlia commented
I know the CATs for h2 haven't been merged yet. But to cut short the 🐔  + 🥚  problem I am merging this knowing that you have run it yourselves.

2021-09-07 15:12 UTC, merged