wip: feat(gorouter): provide option to log more details
cloudfoundry/routing-release pull request #323
Opened 2023-05-10 13:59 UTC by maxmoehl

This commit bumps gorouter to include the new feature flag that allows logging of additional fields in the access log. Those fields provide additional information on the attempts that were performed and the timings of the request. The feature flag is exposed in the gorouter job as `router.log_attempts_details` and defaults to false.

To-Do: bump gorouter once the PR got merged

* [X] I have viewed signed and have submitted the Contributor License Agreement
* [X] I have made this pull request to the `develop` branch
* [ ] I have run all the unit tests using `scripts/run-unit-tests-in-docker`
* [ ] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests on bosh lite
* [ ] (Optional) I have run CF Acceptance Tests on bosh lite

2023-05-17 06:16 UTC, peanball requested changes

2023-05-17 06:16 UTC, peanball commented on jobs/gorouter/templates/gorouter.yml.erb
> +  'attempts_details' => p('router.log_attempts_details'),
This needs adaptation to the new naming in https://github.com/cloudfoundry/gorouter/pull/346.

-> https://github.com/cloudfoundry/gorouter/pull/346/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R151

2023-05-17 06:16 UTC, peanball commented on jobs/gorouter/spec
> +    description: "Log additional fields in the access log that provide more details on the specific timings and attempts performed."
```suggestion
    description: "Log additional fields in the access log that provide more details on the specific timings and attempts performed towards endpoints."
```

2023-05-21 10:25 UTC, peanball commented
Could we get a spec test as well for the new field?

2023-05-23 05:59 UTC, maxmoehl commented
I'm still working on the spec test, but the change itself is ready for review.

2023-05-23 07:09 UTC, peanball approved these changes

2023-06-20 12:29 UTC, domdom82 approved these changes

2023-06-20 12:32 UTC, merged