Add TLS/mTLS support to TCP Router
cloudfoundry/routing-release pull request #422
Opened 2024-06-27 20:34 UTC by Birdrock

- [ ] Read the [Contributing document](../blob/-/.github/CONTRIBUTING.md).

Summary
---------------
Adds TLS/mTLS support to TCP Router.

Backward Compatibility
---------------
Breaking Change? **No**

2024-06-27 20:43 UTC, geofffranks reviewed
BOSH link support was not added for pulling in the CA, because gorouter does not use links to pull in the CA for its backend tls info, and we were mimicking its behavior here.

Additionally rep does not provide a link with its executor's instance identity CA.

2024-07-01 16:38 UTC, ameowlia requested changes

2024-07-01 16:38 UTC, ameowlia commented on jobs/tcp_router/templates/tcp_router.yml.erb
> +<%
Sometimes people accidentally put in spaces or new lines for certs when they don't actually want anything set. Esp when using GUIs to set these properties. 

❓ Can we add a space/newline trim to this logic? And if there were only spaces then it should treat it as if nothing was provided?

2024-07-02 20:33 UTC, Birdrock commented on jobs/tcp_router/templates/tcp_router.yml.erb
> +<%
We definitely can. The block is already trimming trailing white space, so we can trim leading, as well.

2024-07-02 20:39 UTC, Birdrock commented on jobs/tcp_router/templates/tcp_router.yml.erb
> +<%
This looks like an execution block. Is the request to trim `ca_cert`, `client_cert`, and `client_key` individually?

2024-07-08 14:38 UTC, geofffranks commented on jobs/tcp_router/templates/tcp_router.yml.erb
> +<%
Correct, i think we just want to call `.strip` when setting those three variables.

2024-07-08 20:27 UTC, geofffranks commented
Closing as this code was included in #425 with a couple extra commits that addressed PR feedback here + @Birdrock is temporarily on another project and we can't push to his branch.

2024-07-08 20:27 UTC, closed without merging